# Generated by Django 3.0.7 on 2020-07-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailreps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='num_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
