# Generated by Django 3.0.7 on 2020-07-13 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailreps', '0002_issue_num_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailreps.Issue')),
            ],
        ),
    ]
