# Generated by Django 3.0.7 on 2020-07-13 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailreps', '0003_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='num_votes',
        ),
    ]
