# Generated by Django 3.0.7 on 2020-07-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailreps', '0004_remove_issue_num_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='party',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='senator',
            name='party',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
