# Generated by Django 3.0.7 on 2020-07-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailreps', '0005_auto_20200714_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='district',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
